import type { Appliance, Brand } from '../catalog'

/**
 * The assistant's reference: common faults for the five appliances this
 * network services, written the way a senior technician would brief a junior.
 * Everything here is "commonly" or "likely" — the answer engine never turns a
 * match into a confirmed diagnosis.
 */

export interface FaultProfile {
  id: string
  appliance: Appliance
  title: string
  /** Words in the issue or question that point to this fault. */
  keywords: string[]
  category: string
  causes: string[]
  checks: string[]
  repair: string[]
  /** Catalog SKUs, most likely first. */
  parts: { sku: string; likely?: boolean }[]
  /** Parts or consumables not stocked as SKUs. */
  otherParts?: string[]
  safety: string
  customer: string
  notes: { diagnosis: string; action: string; recommendation: string }
}

const POWER = 'Switch off and unplug the appliance (or turn off its MCB) before opening any panel.'

export const FAULTS: FaultProfile[] = [
  /* ------------------------------------------------------------ Washer */
  {
    id: 'washer-drain',
    appliance: 'washer',
    title: 'Not draining',
    keywords: ['drain', 'draining', 'water not going', 'water stays', 'standing water', 'oe', '5e', '5c', 'se', 'e18', 'f18'],
    category: 'Drainage',
    causes: ['Blocked drain / pump filter (coins, lint, hairpins)', 'Kinked or clogged drain hose', 'Faulty drain pump motor', 'Loose pump wiring or connector'],
    checks: [
      'Disconnect power and place a tray under the filter door.',
      'Open the pump filter (front-load) or check the pump inlet (top-load) and clear debris.',
      'Inspect the drain hose for kinks, blockage and correct height (not below 60 cm on most models).',
      'Run a drain/spin cycle and listen: humming with no flow points to a jammed impeller, silence points to pump or wiring.',
      'Measure pump coil resistance (commonly around 150–200 Ω; confirm for the model).',
    ],
    repair: [
      'Clean the filter and flush the sump.',
      'Clear or replace the drain hose if damaged.',
      'If the pump is open-circuit or seized, replace the drain pump motor.',
      'Run a test drain and spin cycle and check for leaks at the filter seal.',
    ],
    parts: [{ sku: 'WM-DP01', likely: true }, { sku: 'WM-DH07' }],
    otherParts: ['Pump filter', 'Pump wiring harness'],
    safety: `${POWER} Drain residual water slowly — it may be hot after a wash cycle.`,
    customer: 'The washing machine could not drain because the drain filter or pump was blocked. We cleaned the drainage path and tested it with a spin cycle.',
    notes: {
      diagnosis: 'Drainage fault — water not being pumped out after the wash cycle.',
      action: 'Drain filter cleaned, drain hose inspected and drainage system tested.',
      recommendation: 'Check pockets before washing and clean the filter monthly. Monitor the next few cycles.',
    },
  },
  {
    id: 'washer-inlet',
    appliance: 'washer',
    title: 'Water not filling',
    keywords: ['not filling', 'no water', 'water not coming', 'inlet', 'fill', 'ie', '4e', '4c', 'e17', 'f17'],
    category: 'Water inlet',
    causes: ['Tap closed or low water pressure', 'Clogged inlet filter mesh', 'Faulty water inlet valve', 'Pressure switch / level sensor fault'],
    checks: [
      'Confirm the tap is open and there is supply pressure.',
      'Disconnect power, remove the inlet hose and clean the filter mesh at the valve.',
      'Check the inlet valve coil for continuity.',
      'Check the pressure hose to the level sensor for blockage or air leaks.',
    ],
    repair: ['Clean the inlet mesh.', 'Replace the inlet valve if the coil is open.', 'Clear or replace the pressure hose if blocked.', 'Run a fill test and check for leaks.'],
    parts: [{ sku: 'WM-IV02', likely: true }],
    otherParts: ['Inlet hose', 'Pressure hose'],
    safety: POWER,
    customer: 'Water was not reaching the machine properly. We cleaned the water inlet and checked the valve that lets water in.',
    notes: {
      diagnosis: 'Water inlet fault — drum not filling to level.',
      action: 'Inlet filter cleaned and inlet valve checked.',
      recommendation: 'Keep the tap fully open during washes. Monitor fill time.',
    },
  },
  {
    id: 'washer-spin',
    appliance: 'washer',
    title: 'Not spinning / drum not rotating',
    keywords: ['not spinning', 'spin', 'drum not', 'not rotating', 'agitat', 'motor', 'belt', 'le', '3e', 'e21', 'f21'],
    category: 'Motor / drive',
    causes: ['Worn or slipped drive belt', 'Unbalanced load stopping the spin', 'Motor carbon brushes worn (brushed motors)', 'Door lock not engaging', 'Motor or PCB drive fault'],
    checks: ['Try a spin with a balanced small load.', 'Disconnect power and check the drive belt condition and tension.', 'Rotate the drum by hand — it should turn freely without grinding.', 'Check motor brushes and connector.'],
    repair: ['Refit or replace the belt.', 'Replace worn brushes if applicable.', 'Test spin at low then high speed.'],
    parts: [{ sku: 'WM-DB03', likely: true }, { sku: 'WM-DL04' }, { sku: 'WM-PC06' }],
    otherParts: ['Motor carbon brushes'],
    safety: POWER,
    customer: 'The drum was not turning at spin speed because of a drive problem. We checked the belt and motor and tested the spin.',
    notes: { diagnosis: 'Drive fault — drum not reaching spin.', action: 'Drive belt and motor checked; spin tested.', recommendation: 'Avoid overloading and spread heavy items evenly.' },
  },
  {
    id: 'washer-noise',
    appliance: 'washer',
    title: 'Noise or heavy vibration',
    keywords: ['noise', 'noisy', 'vibration', 'shaking', 'banging', 'grinding', 'ue', 'ub', 'unbalance', 'walking'],
    category: 'Mechanical / drum',
    causes: ['Machine not level or transit bolts left in', 'Worn shock absorbers / suspension', 'Worn drum bearings (grinding, rumbling)', 'Foreign object between drum and tub'],
    checks: ['Check transit bolts are removed and the machine is level.', 'Push the drum down — it should not bounce repeatedly.', 'Spin the empty drum by hand and listen for rumble.', 'Check between drum and tub for coins or wires.'],
    repair: ['Level the machine.', 'Replace shock absorbers if weak.', 'Bearings usually need a tub strip-down — quote before starting.'],
    parts: [{ sku: 'WM-SA08', likely: true }, { sku: 'WM-BK05' }],
    safety: POWER,
    customer: 'The machine was shaking because its suspension or level was off. We balanced it and checked the parts that absorb vibration.',
    notes: { diagnosis: 'Excess vibration during spin.', action: 'Levelling checked; suspension inspected.', recommendation: 'Keep loads balanced. Monitor for grinding noise.' },
  },
  {
    id: 'washer-leak',
    appliance: 'washer',
    title: 'Leaking water',
    keywords: ['leak', 'leaking', 'water on floor', 'dripping', 'le', 'lc', 'e23', 'f23'],
    category: 'Leakage',
    causes: ['Loose inlet or drain hose clamp', 'Damaged door gasket (front-load)', 'Pump filter seal not seated', 'Cracked tub or detergent drawer overflow'],
    checks: ['Run a short cycle with the back panel off and watch for the leak point.', 'Inspect the door gasket folds for tears.', 'Check hose clamps and filter seal.'],
    repair: ['Tighten or replace clamps and hoses.', 'Replace the gasket if torn.', 'Reseat the filter cap.'],
    parts: [{ sku: 'WM-DH07' }],
    otherParts: ['Door gasket', 'Hose clamps'],
    safety: `${POWER} Keep the floor dry around live parts.`,
    customer: 'Water was leaking from a loose or worn seal. We found the leak point and sealed it.',
    notes: { diagnosis: 'Water leakage during cycle.', action: 'Leak point traced; seals and hoses checked.', recommendation: 'Use the right detergent quantity to avoid overflow.' },
  },
  {
    id: 'washer-start',
    appliance: 'washer',
    title: 'Not starting / door lock',
    keywords: ['not starting', 'wont start', "won't start", 'door lock', 'door error', 'de', 'dc', 'no power', 'dead', 'e16', 'f16'],
    category: 'Electrical / PCB',
    causes: ['Door not latching / faulty door interlock', 'Child lock enabled', 'No supply at the socket', 'Control PCB fault'],
    checks: ['Check the socket supply and plug.', 'Check child lock is off.', 'Close the door firmly and listen for the lock click.', 'Test the interlock for continuity.'],
    repair: ['Replace the door interlock if faulty.', 'If supply and lock are fine, test the PCB before quoting a replacement.'],
    parts: [{ sku: 'WM-DL04', likely: true }, { sku: 'WM-PC06' }],
    safety: POWER,
    customer: 'The machine would not start because the door lock was not engaging. We tested it and fixed the lock.',
    notes: { diagnosis: 'Machine not starting — door lock not engaging.', action: 'Supply, child lock and door interlock tested.', recommendation: 'Close the door firmly before starting.' },
  },

  /* ------------------------------------------------------------ Fridge */
  {
    id: 'fridge-nocool',
    appliance: 'fridge',
    title: 'Not cooling at all',
    keywords: ['not cooling', 'stopped cooling', 'no cooling', 'warm', 'compressor', 'not cold'],
    category: 'Cooling / gas',
    causes: ['Compressor not starting (relay / OLP)', 'Refrigerant leak or low gas', 'Thermostat or temperature sensor fault', 'Inverter PCB fault (inverter models)'],
    checks: [
      'Confirm supply voltage at the socket and the temperature setting.',
      'Listen for the compressor — clicking every few minutes often points to relay/OLP.',
      'Feel the condenser lines: both cold/ambient suggests the compressor is not pumping or gas is low.',
      'Check for oily spots on lines that indicate a leak.',
    ],
    repair: ['Replace relay & OLP if the compressor clicks but does not run.', 'If gas is low, find and fix the leak before recharging.', 'Replace the thermostat or sensor if out of range.'],
    parts: [{ sku: 'RF-RL04', likely: true }, { sku: 'RF-GS05' }, { sku: 'RF-TH01' }, { sku: 'RF-PC08' }],
    safety: `${POWER} Wait 5 minutes after power-off before touching the compressor relay — capacitors may hold charge. R600a is flammable: no open flame.`,
    customer: 'The fridge stopped cooling because the part that starts the cooling motor was not working. We tested the cooling system and fixed the fault.',
    notes: { diagnosis: 'No cooling — compressor not running.', action: 'Supply, relay/OLP and sealed system checked.', recommendation: 'Keep 10 cm clearance behind the fridge. Monitor cooling over 24 hours.' },
  },
  {
    id: 'fridge-lower',
    appliance: 'fridge',
    title: 'Freezer cold, fridge section warm',
    keywords: ['freezer cold', 'lower', 'fridge section', 'bottom not cooling', 'freezer ok', 'defrost', 'ice build', 'frost'],
    category: 'Defrost system',
    causes: ['Defrost system fault causing ice to block the air duct', 'Evaporator fan motor not running', 'Damper stuck closed', 'Defrost timer / sensor fault'],
    checks: ['Remove the freezer back panel and look for a solid ice block on the evaporator.', 'Check the evaporator fan turns and runs with the door switch pressed.', 'Test the defrost heater and bimetal for continuity.'],
    repair: ['Manually defrost the evaporator.', 'Replace the defrost heater, timer or sensor that failed.', 'Replace the fan motor if it does not run.'],
    parts: [{ sku: 'RF-DH03', likely: true }, { sku: 'RF-DT02' }, { sku: 'RF-FM07' }],
    otherParts: ['Defrost bimetal / sensor'],
    safety: POWER,
    customer: 'Ice had built up and blocked cold air from reaching the fridge section. We cleared it and repaired the part that melts the ice automatically.',
    notes: { diagnosis: 'Fridge section warm; freezer cold — airflow blocked by ice.', action: 'Evaporator defrosted; defrost system and fan tested.', recommendation: 'Avoid overfilling that blocks vents. Monitor over 48 hours.' },
  },
  {
    id: 'fridge-leak',
    appliance: 'fridge',
    title: 'Water leaking',
    keywords: ['leak', 'water inside', 'water under', 'dripping', 'puddle'],
    category: 'Leakage',
    causes: ['Blocked defrost drain', 'Drain pan cracked or misplaced', 'Door gasket not sealing'],
    checks: ['Pour warm water in the drain hole and see if it flows.', 'Check the drain pan under the fridge.', 'Close a paper strip in the door — it should hold.'],
    repair: ['Clear the drain line.', 'Refit or replace the drain pan.', 'Replace the gasket if not sealing.'],
    parts: [{ sku: 'RF-GK06' }],
    otherParts: ['Drain pan'],
    safety: POWER,
    customer: 'Water from the automatic defrost was not draining away. We cleared the drain.',
    notes: { diagnosis: 'Water leakage from defrost drain.', action: 'Drain line cleared and drain pan checked.', recommendation: 'Keep food away from the rear wall.' },
  },
  {
    id: 'fridge-noise',
    appliance: 'fridge',
    title: 'Noise',
    keywords: ['noise', 'noisy', 'buzz', 'rattle', 'humming', 'clicking'],
    category: 'Compressor',
    causes: ['Fan blade hitting ice or the housing', 'Loose compressor mounts', 'Relay clicking on a failed start'],
    checks: ['Find where the noise is from: freezer (fan), back bottom (compressor), condenser fan.', 'Check fan blades for ice contact.', 'Check compressor rubber mounts.'],
    repair: ['Clear ice or replace the fan.', 'Tighten or replace mounts.'],
    parts: [{ sku: 'RF-FM07' }, { sku: 'RF-RL04' }],
    safety: POWER,
    customer: 'The noise came from a fan or loose mounting. We found the source and fixed it.',
    notes: { diagnosis: 'Abnormal noise during operation.', action: 'Noise source located; fans and mounts checked.', recommendation: 'Keep the fridge level on a firm floor.' },
  },

  /* ------------------------------------------------------------ Oven */
  {
    id: 'oven-noheat',
    appliance: 'oven',
    title: 'Not heating',
    keywords: ['not heating', 'no heat', 'cold', 'element', 'heating', 'not getting hot'],
    category: 'Heating',
    causes: ['Heating element open-circuit', 'Blown thermal fuse', 'Faulty thermostat or temperature sensor', 'Control PCB relay fault'],
    checks: ['Check the element visibly for breaks or blistering.', 'Test element resistance (commonly 20–40 Ω for 1–2 kW; confirm for the model).', 'Check the thermal fuse for continuity.', 'Test the thermostat or sensor against a meter.'],
    repair: ['Replace the failed element.', 'Replace the thermal fuse — and find why it blew (fan, vent blocked).', 'Replace the thermostat if out of range.'],
    parts: [{ sku: 'OV-HT01', likely: true }, { sku: 'OV-HB02' }, { sku: 'OV-TF06' }, { sku: 'OV-TS03' }],
    safety: `${POWER} Built-in ovens are hard-wired: isolate at the MCB and confirm with a tester.`,
    customer: 'The oven was not heating because the heating part had failed. We tested it and replaced what was faulty.',
    notes: { diagnosis: 'Oven not heating.', action: 'Elements, thermal fuse and thermostat tested.', recommendation: 'Preheat before use and keep vents clear.' },
  },
  {
    id: 'oven-uneven',
    appliance: 'oven',
    title: 'Uneven cooking / fan not working',
    keywords: ['uneven', 'fan', 'convection', 'one side', 'burns', 'not even'],
    category: 'Fan / convection',
    causes: ['Convection fan motor failed', 'Fan blade loose', 'One element not working'],
    checks: ['Run convection mode and check the fan turns.', 'Check fan blade fixing.', 'Check both elements heat.'],
    repair: ['Replace the fan motor or refix the blade.', 'Replace a failed element.'],
    parts: [{ sku: 'OV-FM04', likely: true }, { sku: 'OV-HB02' }],
    safety: POWER,
    customer: 'The fan that spreads heat was not working, so food cooked unevenly. We repaired it.',
    notes: { diagnosis: 'Uneven heating — convection fan fault.', action: 'Fan motor and elements tested.', recommendation: 'Use the middle shelf for even results.' },
  },
  {
    id: 'oven-temp',
    appliance: 'oven',
    title: 'Overheating / wrong temperature',
    keywords: ['overheat', 'too hot', 'temperature', 'burning', 'thermostat', 'sensor'],
    category: 'Thermostat / sensor',
    causes: ['Temperature sensor out of range', 'Thermostat stuck', 'Relay welded on the PCB'],
    checks: ['Compare actual temperature with an oven thermometer at 180 °C.', 'Measure sensor resistance at room temperature (often ~1,000–1,100 Ω for PT1000 types; confirm).'],
    repair: ['Replace the sensor or thermostat.', 'If a relay is welded, repair or replace the PCB.'],
    parts: [{ sku: 'OV-TS03', likely: true }, { sku: 'OV-PC07' }],
    safety: POWER,
    customer: 'The oven was reading its temperature wrongly. We checked the sensor and fixed it.',
    notes: { diagnosis: 'Temperature control fault.', action: 'Sensor and thermostat tested against a thermometer.', recommendation: 'Monitor the first few bakes.' },
  },

  /* ------------------------------------------------------------ AC */
  {
    id: 'ac-cooling',
    appliance: 'ac',
    title: 'Weak or no cooling',
    keywords: ['not cooling', 'weak cooling', 'less cooling', 'no cooling', 'warm air', 'blowing warm', 'gas'],
    category: 'Cooling / gas',
    causes: ['Dirty filters or indoor coil', 'Low refrigerant (leak)', 'Outdoor unit not running — capacitor or contactor', 'Outdoor fan not running'],
    checks: [
      'Check and clean the indoor filters.',
      'Confirm the outdoor unit starts: compressor and fan both running.',
      'Measure suction pressure (R32 split: typically around 115–145 psi in cooling; confirm).',
      'Check the run capacitor value against its label.',
      'Look for oil marks at flare joints indicating a leak.',
    ],
    repair: ['Service filters and coil.', 'Replace a weak capacitor or failed contactor.', 'Find and fix leaks before topping up refrigerant.'],
    parts: [{ sku: 'AC-CP01', likely: true }, { sku: 'AC-GS02' }, { sku: 'AC-CN07' }, { sku: 'AC-OF04' }],
    safety: `${POWER} Discharge the capacitor before testing. Use gloves and eye protection when handling refrigerant.`,
    customer: 'The AC was cooling less because of a fault in the outdoor unit or low gas. We checked the system and repaired it.',
    notes: { diagnosis: 'Weak cooling.', action: 'Filters cleaned; outdoor unit, capacitor and pressures checked.', recommendation: 'Clean filters every 2 weeks in summer.' },
  },
  {
    id: 'ac-drip',
    appliance: 'ac',
    title: 'Water dripping from indoor unit',
    keywords: ['dripping', 'water dripping', 'leak', 'water leak', 'drain', 'indoor unit water'],
    category: 'Drainage',
    causes: ['Blocked drain tray or pipe', 'Indoor unit not level', 'Iced coil from low gas or dirty filter'],
    checks: ['Pour water in the drain tray and see if it drains outside.', 'Check the unit slope toward the drain.', 'Check for ice on the indoor coil.'],
    repair: ['Flush or blow out the drain pipe.', 'Re-level the unit.', 'Fix the cause of icing.'],
    parts: [{ sku: 'AC-DP08', likely: true }],
    safety: POWER,
    customer: 'Water was dripping because the pipe that carries it outside was blocked. We cleaned it and checked the flow.',
    notes: { diagnosis: 'Water dripping from indoor unit.', action: 'Drain tray and pipe flushed; slope checked.', recommendation: 'Service the AC before summer.' },
  },
  {
    id: 'ac-power',
    appliance: 'ac',
    title: 'Not turning on / outdoor not starting',
    keywords: ['not turning on', 'not starting', 'no power', 'dead', 'remote', 'outdoor not', 'tripping'],
    category: 'Electrical / PCB',
    causes: ['No supply or stabiliser cut-off', 'Remote batteries or receiver', 'Indoor PCB fault', 'Communication fault between units'],
    checks: ['Check supply and stabiliser output.', 'Test the remote with a phone camera (IR light).', 'Check indoor PCB fuse and error display.', 'Check the inter-connecting cable.'],
    repair: ['Replace the PCB fuse or PCB if faulty.', 'Repair the interconnecting cable.'],
    parts: [{ sku: 'AC-PC05' }, { sku: 'AC-CN07' }, { sku: 'AC-TH06' }],
    safety: POWER,
    customer: 'The AC was not starting because of an electrical fault. We tested the supply and control board.',
    notes: { diagnosis: 'AC not starting.', action: 'Supply, remote and PCB tested.', recommendation: 'Use a suitable stabiliser.' },
  },
  {
    id: 'ac-noise',
    appliance: 'ac',
    title: 'Noise or bad smell',
    keywords: ['noise', 'noisy', 'smell', 'odour', 'odor', 'rattle', 'vibration'],
    category: 'Airflow / fan',
    causes: ['Dirty blower wheel or coil (smell)', 'Loose panels or fan blade', 'Failing fan bearing'],
    checks: ['Inspect the blower wheel for dirt.', 'Check fan blade and mounts.'],
    repair: ['Jet-wash the coil and blower.', 'Tighten or replace the fan.'],
    parts: [{ sku: 'AC-FM03' }],
    safety: POWER,
    customer: 'Dirt inside the AC caused the noise and smell. We cleaned the inside parts.',
    notes: { diagnosis: 'Noise / odour from indoor unit.', action: 'Blower and coil cleaned; fan checked.', recommendation: 'Service every 6 months.' },
  },

  /* ------------------------------------------------------------ Geyser */
  {
    id: 'geyser-trip',
    appliance: 'geyser',
    title: 'Tripping the MCB / RCCB',
    keywords: ['tripping', 'trip', 'mcb', 'rccb', 'elcb', 'shock', 'earth'],
    category: 'Electrical / tripping',
    causes: ['Heating element shorted to earth (scale or corrosion)', 'Water in the terminal area', 'Damaged wiring'],
    checks: ['Isolate supply and remove the terminal cover.', 'Measure insulation resistance of the element to body (should be very high; low reading means leakage).', 'Check for moisture or burnt marks at terminals.'],
    repair: ['Replace the heating element and descale the tank.', 'Replace the anode rod if eaten away.', 'Replace burnt wiring.'],
    parts: [{ sku: 'GY-HE01', likely: true }, { sku: 'GY-AR04' }],
    safety: `${POWER} Do not reset the breaker repeatedly — earth leakage on a water heater is a shock risk.`,
    customer: 'The geyser was tripping the power switch because its heating part was leaking current. We replaced the faulty part for safety.',
    notes: { diagnosis: 'Geyser tripping MCB/RCCB — earth leakage.', action: 'Element insulation tested; terminals inspected.', recommendation: 'Descale yearly in hard-water areas.' },
  },
  {
    id: 'geyser-noheat',
    appliance: 'geyser',
    title: 'Not heating',
    keywords: ['not heating', 'cold water', 'no hot', 'not hot', 'indicator'],
    category: 'Heating element',
    causes: ['Element open-circuit', 'Thermostat faulty', 'Thermal cut-out tripped'],
    checks: ['Check supply at the terminals.', 'Test element resistance (2 kW ≈ 26 Ω).', 'Reset or test the thermal cut-out.', 'Test the thermostat.'],
    repair: ['Replace the element or thermostat.', 'Replace the cut-out if it will not reset.'],
    parts: [{ sku: 'GY-HE01', likely: true }, { sku: 'GY-TH02' }, { sku: 'GY-TC05' }],
    safety: POWER,
    customer: 'The geyser was not heating because the heating part stopped working. We replaced it.',
    notes: { diagnosis: 'Geyser not heating.', action: 'Element, thermostat and cut-out tested.', recommendation: 'Set the thermostat to a moderate temperature.' },
  },
  {
    id: 'geyser-leak',
    appliance: 'geyser',
    title: 'Leaking or sparking',
    keywords: ['leak', 'leaking', 'sparking', 'spark', 'burning smell', 'water from bottom', 'dripping'],
    category: 'Leakage',
    causes: ['Loose inlet/outlet connector', 'Element flange gasket failed', 'Tank corrosion (serious)', 'Water reaching the electrical terminals (sparking)'],
    checks: ['Isolate power at the MCB first — sparking with water present is dangerous.', 'Find whether water is at connectors, element flange or tank seam.', 'Inspect terminals for burning.'],
    repair: ['Replace connector pipes or gasket.', 'If the tank itself leaks, recommend replacement — do not patch.', 'Replace burnt terminals and wiring.'],
    parts: [{ sku: 'GY-CP06', likely: true }, { sku: 'GY-HE01' }, { sku: 'GY-SV03' }],
    otherParts: ['Element flange gasket'],
    safety: 'Sparking near water: isolate at the MCB before approaching, confirm dead with a tester, and keep the customer away until safe.',
    customer: 'Water was leaking near the electrical parts, which is unsafe. We switched off power, found the leak and fixed it.',
    notes: { diagnosis: 'Water leakage with sparking near switch.', action: 'Power isolated; leak point and terminals inspected.', recommendation: 'Do not use the geyser until repairs are complete.' },
  },
  {
    id: 'geyser-hot',
    appliance: 'geyser',
    title: 'Too hot / steam from valve',
    keywords: ['too hot', 'steam', 'valve', 'overheat', 'boiling', 'pressure'],
    category: 'Valve / pressure',
    causes: ['Thermostat stuck closed', 'Safety valve faulty', 'Thermal cut-out not operating'],
    checks: ['Check outlet water temperature.', 'Check the thermostat cuts off.', 'Operate the safety valve lever.'],
    repair: ['Replace thermostat and safety valve.'],
    parts: [{ sku: 'GY-TH02', likely: true }, { sku: 'GY-SV03' }, { sku: 'GY-TC05' }],
    safety: `${POWER} Hot water and steam can scald — let the tank cool before work.`,
    customer: 'The geyser was overheating because its temperature control failed. We replaced the faulty part.',
    notes: { diagnosis: 'Overheating / valve discharging.', action: 'Thermostat and safety valve tested.', recommendation: 'Never block the safety valve.' },
  },
]

/**
 * Error codes the assistant can explain, per brand and appliance. Codes vary
 * across model series, so every answer tells the technician to confirm
 * against the service manual. An empty list means "not in the reference".
 */
export const ERROR_CODES: Partial<Record<Brand, Partial<Record<Appliance, Record<string, { meaning: string; fault: string }>>>>> = {
  samsung: {
    washer: {
      '4C': { meaning: 'Water supply error — not filling in time', fault: 'washer-inlet' },
      '4E': { meaning: 'Water supply error — not filling in time', fault: 'washer-inlet' },
      '5C': { meaning: 'Drain error — water not pumped out in time', fault: 'washer-drain' },
      '5E': { meaning: 'Drain error — water not pumped out in time', fault: 'washer-drain' },
      SE: { meaning: 'Drain error (older models)', fault: 'washer-drain' },
      UE: { meaning: 'Unbalanced load during spin', fault: 'washer-noise' },
      UB: { meaning: 'Unbalanced load during spin', fault: 'washer-noise' },
      DC: { meaning: 'Door open or door lock fault', fault: 'washer-start' },
      DE: { meaning: 'Door open or door lock fault', fault: 'washer-start' },
      LC: { meaning: 'Water leak detected / drain level problem', fault: 'washer-leak' },
      LE: { meaning: 'Water leak detected / drain level problem', fault: 'washer-leak' },
      '3C': { meaning: 'Motor drive fault', fault: 'washer-spin' },
      '3E': { meaning: 'Motor drive fault', fault: 'washer-spin' },
    },
    fridge: {
      '1E': { meaning: 'Ambient temperature sensor fault', fault: 'fridge-nocool' },
      '5E': { meaning: 'Freezer defrost sensor fault', fault: 'fridge-lower' },
      '21E': { meaning: 'Freezer fan fault', fault: 'fridge-lower' },
      '22E': { meaning: 'Fridge fan fault', fault: 'fridge-lower' },
    },
    ac: {
      E101: { meaning: 'Communication error between indoor and outdoor units', fault: 'ac-power' },
      E121: { meaning: 'Indoor room temperature sensor fault', fault: 'ac-power' },
      E122: { meaning: 'Indoor coil (evaporator) sensor fault', fault: 'ac-cooling' },
      E154: { meaning: 'Indoor fan motor fault', fault: 'ac-noise' },
      E554: { meaning: 'Refrigerant leak detected', fault: 'ac-cooling' },
    },
  },
  lg: {
    washer: {
      OE: { meaning: 'Drain error — water not drained in time', fault: 'washer-drain' },
      IE: { meaning: 'Inlet error — water not filling in time', fault: 'washer-inlet' },
      UE: { meaning: 'Unbalanced load', fault: 'washer-noise' },
      DE: { meaning: 'Door not closed / door lock fault', fault: 'washer-start' },
      LE: { meaning: 'Motor locked or overloaded', fault: 'washer-spin' },
      FE: { meaning: 'Overfill — too much water', fault: 'washer-inlet' },
      PE: { meaning: 'Water level (pressure) sensor fault', fault: 'washer-inlet' },
    },
    fridge: {
      'ER FF': { meaning: 'Freezer fan fault', fault: 'fridge-lower' },
      'ER DH': { meaning: 'Defrost heater / defrost fault', fault: 'fridge-lower' },
      'ER RS': { meaning: 'Fridge temperature sensor fault', fault: 'fridge-nocool' },
      'ER FS': { meaning: 'Freezer temperature sensor fault', fault: 'fridge-nocool' },
      'ER CO': { meaning: 'Communication error between boards', fault: 'fridge-nocool' },
    },
    ac: {
      CH01: { meaning: 'Indoor air temperature sensor fault', fault: 'ac-power' },
      CH02: { meaning: 'Indoor pipe temperature sensor fault', fault: 'ac-cooling' },
      CH05: { meaning: 'Communication error between indoor and outdoor units', fault: 'ac-power' },
      CH10: { meaning: 'Indoor fan motor fault', fault: 'ac-noise' },
      CH38: { meaning: 'Low refrigerant detected (on many inverter models)', fault: 'ac-cooling' },
    },
  },
  bosch: {
    washer: {
      E17: { meaning: 'Water not filling (inlet)', fault: 'washer-inlet' },
      F17: { meaning: 'Water not filling (inlet)', fault: 'washer-inlet' },
      E18: { meaning: 'Drain error — pump or blockage', fault: 'washer-drain' },
      F18: { meaning: 'Drain error — pump or blockage', fault: 'washer-drain' },
      E23: { meaning: 'Leak detected in base (AquaStop)', fault: 'washer-leak' },
      F23: { meaning: 'Leak detected in base (AquaStop)', fault: 'washer-leak' },
      E21: { meaning: 'Motor / drum not turning', fault: 'washer-spin' },
      F21: { meaning: 'Motor / drum not turning', fault: 'washer-spin' },
      E16: { meaning: 'Door not closed', fault: 'washer-start' },
      F16: { meaning: 'Door not closed', fault: 'washer-start' },
    },
  },
}
