// Copies the web app's public images, clips and demo bundle into the native
// app, and writes the lookup that turns a web path ('/photos/geyser/1.jpg')
// into a bundled asset.
//
// The catalog — seed data, the demo bundle, every component — names its
// pictures by web path. React Native can only bundle a file it sees in a
// static require(), so the map is generated rather than hand-kept: a picture
// added to frontend/public is one `npm run sync:public` away from the app.

import { cpSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(root, '..', 'frontend', 'public')
const target = join(root, 'assets', 'public')

const FOLDERS = ['appliances', 'banners', 'brands', 'photos', 'reels', 'services', 'icons']
const EXTENSIONS = /\.(jpg|jpeg|png|webp|svg|mp4)$/i

rmSync(target, { recursive: true, force: true })
mkdirSync(target, { recursive: true })
for (const folder of FOLDERS) {
  cpSync(join(source, folder), join(target, folder), { recursive: true })
}
cpSync(join(source, 'demo-data.bundle'), join(target, 'demo-data.bundle'))

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    return statSync(path).isDirectory() ? walk(path) : [path]
  })
}

const files = walk(target)
  .filter((path) => EXTENSIONS.test(path))
  .map((path) => relative(target, path).split(sep).join('/'))
  .sort()

const lines = files.map(
  (file) => `  '/${file}': require('../../assets/public/${file}'),`
)

writeFileSync(
  join(root, 'src', 'lib', 'publicAssets.generated.ts'),
  `// Generated by scripts/sync-public.mjs. Do not edit by hand.\n\n` +
    `export const PUBLIC_ASSETS: Record<string, number> = {\n${lines.join('\n')}\n}\n`
)

console.log(`Synced ${files.length} assets from frontend/public`)
